{% set name = "dill" %}
{% set version = "0.3.7" %}

package:
  name: dill
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dill-{{ version }}.tar.gz
  sha256: cc1c8b182eb3013e24bd475ff2e9295af86c1a38eb1aff128dac8962a9ce3c03

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - dill
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uqfoundation/dill
  summary: serialize all of Python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    `dill` extends Python's `pickle` module for serializing and
    de-serializing Python objects to the majority of the built-in
    Python types.
  doc_url: http://trac.mystic.cacr.caltech.edu/project/pathos/wiki/dill.html
  dev_url: https://github.com/uqfoundation/dill

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar
